backend:
  name: github
  repo: Poeticode/AlphaCodes # Path to your Github repository
  branch: master # Branch to update

media_folder: "build/images/uploads"

collections:
  - name: "poetry" # Used in routes, e.g., /admin/collections/blog
    label: "Poetry" # Used in the UI
    folder: "src/poetry" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "poem"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
